server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

#eureka:
#  instance:
#    prefer-ip-address: true  # Use IP address in the service registration
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    enabled: true
#    service-url:
#      defaultZone: http://localhost:8762/eureka  # URL of the Eureka server

# Add any additional application-specific configurations here
